# Generated by Django 5.2.4 on 2025-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
