# Generated by Django 5.2.4 on 2025-08-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
